In [1]:
import scipy
import numpy as np
import matplotlib.pyplot as plt
import essentia
import json
import glob
import gzip
import bz2
import csv

In [2]:
import pandas as pd
import seaborn as sns
from sklearn import mixture

In [3]:
import essentia.standard as estd
import essentia.streaming as estr

In [4]:
json.data = []
feat = []

In [5]:
feat

[]

In [6]:
#def total_area_bz2('./acousticbrainz-2015-01-selected-features.csv.bz2'):
#    with bz2.BZ2File('./acousticbrainz-2015-01-selected-features.csv.bz2') as f
#        return sum_area(f)

#input_file = bz2.BZ2File('./acousticbrainz-2015-01-selected-features.csv.bz2', 'rb')
#try:
#    print input_file.read()
#finally:
#    input_file.close()

In [7]:
#LOAD DESCRIPTORS DB

#for filename in glob.glob('./testDB/*.json'):
#    json.data.append(open(filename).read())

with open("./testDB/last_fm.csv", "rb") as f:
    line=[line.split() for line in f]  

In [8]:
#CorLine = np.chararray(6301*348).reshape(6301, 348)


In [9]:
#for i in range (0,len(line)-1):
#    CorLine[i] = str(line[i]).split(',')
CorList = []

for i in range (0,6301):
    CorLine = []
    CorLine.append(str(line[i]).split(','))
    CorList.append(str(CorLine[0]).split(','))

In [10]:
A =CorList[2][2][2:len(CorList[7][25])-1]
A

'12.87817478'

In [11]:
AsianList = []
for i in range(1,451):
    for j in range(2,270):
        AsianList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [12]:
BluesList = []
for i in range(451,901):
    for j in range(2,270):
        BluesList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [13]:
ClassicalList = []
for i in range(901,1351):
    for j in range(2,270):
        ClassicalList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [14]:
ClatinamerList = []
for i in range(1351,1801):
    for j in range(2,270):
        ClatinamerList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [15]:
CountryList = []
for i in range(1801,2251):
    for j in range(2,270):
        CountryList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [16]:
EasyList = []
for i in range(2251,2701):
    for j in range(2,270):
        EasyList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [17]:
ElectronicList = []
for i in range(2701,3151):
    for j in range(2,270):
        ElectronicList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [18]:
FolkList = []
for i in range(3151,3601):
    for j in range(2,270):
        FolkList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [19]:
HiphopList = []
for i in range(3601,4051):
    for j in range(2,270):
        HiphopList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [20]:
JazzList = []
for i in range(4051,4501):
    for j in range(2,270):
        JazzList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [21]:
PopList = []
for i in range(4501,4951):
    for j in range(2,270):
        PopList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [22]:
RnbList = []
for i in range(4951,5401):
    for j in range(2,270):
        RnbList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [23]:
RockList = []
for i in range(5401,5851):
    for j in range(2,270):
        RockList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [24]:
SkaList = []
for i in range(5851,6301):
    for j in range(2,270):
        SkaList.append(CorList[i][j][2:len(CorList[i][j])-1])

In [25]:
len(AsianList)

120600

In [26]:
Asian = np.zeros([450,268])
Blues = np.zeros([450,268])
Classical = np.zeros([450,268])
Clatinamer = np.zeros([450,268])
Country =  np.zeros([450,268])
Easy = np.zeros([450,268])
Electronic = np.zeros([450,268])
Folk = np.zeros([450,268])
Hiphop = np.zeros([450,268])
Jazz = np.zeros([450,268])
Pop = np.zeros([450,268])
Rnb = np.zeros([450,268])
Rock = np.zeros([450,268])
Ska = np.zeros([450,268])


In [27]:
k = 0
for i in range (0,450):
    for j in range (0,268):
        Asian[i][j] = AsianList[k]
        Blues[i][j] = BluesList[k]
        Classical[i][j] = ClassicalList[k]
        Clatinamer[i][j] = ClatinamerList[k]
        Country[i][j] = CountryList[k]
        Easy[i][j] = EasyList[k]
        Electronic[i][j] = ElectronicList[k]
        Folk[i][j] = FolkList[k]
        Hiphop[i][j] = HiphopList[k]
        Jazz[i][j] = JazzList[k]
        Pop[i][j] = PopList[k]
        Rnb[i][j] = RnbList[k]
        Rock[i][j] = RockList[k]
        Ska[i][j] = SkaList[k]
        k = k+1
    

In [28]:
Asian[0][266]

9.5537738799999996

In [29]:
FeatAsian = np.zeros(len(Asian))
FeatBlues = np.zeros(len(Blues))
FeatClassical = np.zeros(len(Classical))
FeatClatinamer = np.zeros(len(Clatinamer))
FeatCountry = np.zeros(len(Country))
FeatEasy = np.zeros(len(Easy))
FeatElectronic = np.zeros(len(Electronic))
FeatFolk = np.zeros(len(Folk))
FeatHiphop = np.zeros(len(Hiphop))
FeatJazz = np.zeros(len(Jazz))
FeatPop = np.zeros(len(Pop))
FeatRnb = np.zeros(len(Rnb))
FeatRock = np.zeros(len(Rock))
FeatSka = np.zeros(len(Ska))

In [30]:
numFeat = 4
for i in range(0,len(FeatAsian)):
    FeatAsian[i] = Asian[i][numFeat]
    FeatBlues[i] = Blues[i][numFeat]
    FeatClassical[i] = Classical[i][numFeat]    
    FeatClatinamer[i] = Clatinamer[i][numFeat]   
    FeatCountry[i] = Country[i][numFeat]
    FeatEasy[i] = Easy[i][numFeat]
    FeatElectronic[i] = Electronic[i][numFeat]
    FeatFolk[i] = Folk[i][numFeat]
    FeatHiphop[i] = Hiphop[i][numFeat]
    FeatJazz[i] = Jazz[i][numFeat]
    FeatPop[i] = Pop[i][numFeat]
    FeatRnb[i] = Rnb[i][numFeat]
    FeatRock[i] = Rock[i][numFeat]
    FeatSka[i] = Ska[i][numFeat]

In [35]:
sns.distplot(FeatAsian) #b
sns.distplot(FeatBlues) #g
sns.distplot(FeatClassical) #r
sns.distplot(FeatClatinamer) #p
sns.distplot(FeatCountry) #y
sns.distplot(FeatEasy) #c
sns.distplot(FeatElectronic) #b
sns.distplot(FeatFolk) #g
sns.distplot(FeatHiphop) #r
sns.distplot(FeatJazz) #p
sns.distplot(FeatPop) #y
sns.distplot(FeatRnb) #c
sns.distplot(FeatRock) #b
sns.distplot(FeatSka) #g

#6 colors

In [36]:
plt.show()

In [61]:
plt.boxplot([x for x in [FeatAsian,FeatBlues,FeatClassical,FeatClatinamer,FeatCountry,FeatEasy,FeatElectronic,FeatFolk,FeatHiphop,FeatJazz,FeatPop,FeatRnb,FeatRock,FeatSka]], 0, 'rs', 1)
plt.xticks([y+1 for y in range(len([FeatAsian,FeatBlues,FeatClassical,FeatClatinamer,FeatCountry,FeatEasy,FeatElectronic,FeatFolk,FeatHiphop,FeatJazz,FeatPop,FeatRnb,FeatRock,FeatSka]))], ['FeatAsian','FeatBlues','FeatClassical','FeatClatinamer','FeatCountry','FeatEasy','FeatElectronic','FeatFolk','FeatHiphop','FeatJazz','FeatPop','FeatRnb','FeatRock','FeatSka'])

([<matplotlib.axis.XTick at 0x951e43ac>,
 <a list of 14 Text xticklabel objects>)

In [62]:
plt.show()

In [65]:
meanFeats = np.zeros((14,3))
meanFeats

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [71]:
i = 0
for genre in [FeatAsian,FeatBlues,FeatClassical,FeatClatinamer,FeatCountry,FeatEasy,FeatElectronic,FeatFolk,FeatHiphop,FeatJazz,FeatPop,FeatRnb,FeatRock,FeatSka]:
    meanFeats[i][0] = i
    meanFeats[i][1] = np.mean(genre)
    meanFeats[i][2] = np.var(genre)
    i = i+1

In [72]:
meanFeats

array([[  0.00000000e+00,   9.95155549e+01,   1.73324738e+03],
       [  1.00000000e+00,   6.55395298e+01,   1.56795966e+03],
       [  2.00000000e+00,   5.07176102e+01,   1.40487736e+03],
       [  3.00000000e+00,   8.40824076e+01,   1.55589254e+03],
       [  4.00000000e+00,   6.58094363e+01,   1.05261921e+03],
       [  5.00000000e+00,   5.91434886e+01,   1.37415655e+03],
       [  6.00000000e+00,   1.19275116e+02,   3.84802167e+03],
       [  7.00000000e+00,   5.29205829e+01,   1.08077456e+03],
       [  8.00000000e+00,   1.17992420e+02,   1.72564971e+03],
       [  9.00000000e+00,   5.61200303e+01,   1.45751127e+03],
       [  1.00000000e+01,   9.57606635e+01,   2.18153163e+03],
       [  1.10000000e+01,   8.66889433e+01,   1.51446616e+03],
       [  1.20000000e+01,   1.13132564e+02,   2.75064590e+03],
       [  1.30000000e+01,   1.13540186e+02,   1.87636175e+03]])

In [79]:
normMeanFeats = meanFeats
normMeanFeats[:,2] = (meanFeats[:,2]-min(meanFeats[:,2]))/(max(meanFeats[:,2])-min(meanFeats[:,2]))
normMeanFeats[:,1] = (meanFeats[:,1]-min(meanFeats[:,1]))/(max(meanFeats[:,1])-min(meanFeats[:,1]))

In [102]:
normMeanFeats

array([[  0.00000000e+00,   7.11781214e-01,   2.43481280e-01],
       [  1.00000000e+00,   2.16196890e-01,   1.84352866e-01],
       [  2.00000000e+00,   0.00000000e+00,   1.26013393e-01],
       [  3.00000000e+00,   4.86668776e-01,   1.80036090e-01],
       [  4.00000000e+00,   2.20133826e-01,   0.00000000e+00],
       [  5.00000000e+00,   1.22902348e-01,   1.15023629e-01],
       [  6.00000000e+00,   1.00000000e+00,   1.00000000e+00],
       [  7.00000000e+00,   3.21332089e-02,   1.00720201e-02],
       [  8.00000000e+00,   9.81290221e-01,   2.40763364e-01],
       [  9.00000000e+00,   7.88012929e-02,   1.44842136e-01],
       [  1.00000000e+01,   6.57011260e-01,   4.03846114e-01],
       [  1.10000000e+01,   5.24688474e-01,   1.65216622e-01],
       [  1.20000000e+01,   9.10402924e-01,   6.07435500e-01],
       [  1.30000000e+01,   9.16348619e-01,   2.94677618e-01]])

In [144]:
plt.plot(normMeanFeats[:,1],'o')
plt.plot(normMeanFeats[:,2],'o')

In [145]:
plt.show()

In [103]:
from operator import itemgetter
OrdNormMeanFeats = np.zeros((14,3))
OrdNormMeanFeats = sorted(normMeanFeats,key=itemgetter(1))

In [150]:
OrdNormMeanFeats

[array([ 2.        ,  0.        ,  0.12601339]),
 array([ 7.        ,  0.03213321,  0.01007202]),
 array([ 9.        ,  0.07880129,  0.14484214]),
 array([ 5.        ,  0.12290235,  0.11502363]),
 array([ 1.        ,  0.21619689,  0.18435287]),
 array([ 4.        ,  0.22013383,  0.        ]),
 array([ 3.        ,  0.48666878,  0.18003609]),
 array([ 11.        ,   0.52468847,   0.16521662]),
 array([ 10.        ,   0.65701126,   0.40384611]),
 array([ 0.        ,  0.71178121,  0.24348128]),
 array([ 12.        ,   0.91040292,   0.6074355 ]),
 array([ 13.        ,   0.91634862,   0.29467762]),
 array([ 8.        ,  0.98129022,  0.24076336]),
 array([ 6.,  1.,  1.])]

In [154]:
OrdNormMeanFeats2 = np.zeros((14,3))
for i in range (0,14):
    OrdNormMeanFeats2[i]=OrdNormMeanFeats[i]

In [155]:
OrdNormMeanFeats2

array([[  2.00000000e+00,   0.00000000e+00,   1.26013393e-01],
       [  7.00000000e+00,   3.21332089e-02,   1.00720201e-02],
       [  9.00000000e+00,   7.88012929e-02,   1.44842136e-01],
       [  5.00000000e+00,   1.22902348e-01,   1.15023629e-01],
       [  1.00000000e+00,   2.16196890e-01,   1.84352866e-01],
       [  4.00000000e+00,   2.20133826e-01,   0.00000000e+00],
       [  3.00000000e+00,   4.86668776e-01,   1.80036090e-01],
       [  1.10000000e+01,   5.24688474e-01,   1.65216622e-01],
       [  1.00000000e+01,   6.57011260e-01,   4.03846114e-01],
       [  0.00000000e+00,   7.11781214e-01,   2.43481280e-01],
       [  1.20000000e+01,   9.10402924e-01,   6.07435500e-01],
       [  1.30000000e+01,   9.16348619e-01,   2.94677618e-01],
       [  8.00000000e+00,   9.81290221e-01,   2.40763364e-01],
       [  6.00000000e+00,   1.00000000e+00,   1.00000000e+00]])

In [178]:
plt.plot(OrdNormMeanFeats2[:,1],'-')
plt.plot(OrdNormMeanFeats2[:,1],'o')
plt.plot(OrdNormMeanFeats2[:,2],'o')

In [179]:
plt.show()

In [179]:
FeatAsian1 = np.zeros(len(Asian))
FeatBlues1 = np.zeros(len(Blues))
FeatClassical1 = np.zeros(len(Classical))
FeatClatinamer1 = np.zeros(len(Clatinamer))
FeatCountry1 = np.zeros(len(Country))
FeatEasy1 = np.zeros(len(Easy))
FeatElectronic1 = np.zeros(len(Electronic))
FeatFolk1 = np.zeros(len(Folk))
FeatHiphop1 = np.zeros(len(Hiphop))
FeatJazz1 = np.zeros(len(Jazz))
FeatPop1 = np.zeros(len(Pop))
FeatRnb1 = np.zeros(len(Rnb))
FeatRock1 = np.zeros(len(Rock))
FeatSka1 = np.zeros(len(Ska))

FeatAsian2 = np.zeros(len(Asian))
FeatBlues2 = np.zeros(len(Blues))
FeatClassical2 = np.zeros(len(Classical))
FeatClatinamer2 = np.zeros(len(Clatinamer))
FeatCountry2 = np.zeros(len(Country))
FeatEasy2 = np.zeros(len(Easy))
FeatElectronic2 = np.zeros(len(Electronic))
FeatFolk2 = np.zeros(len(Folk))
FeatHiphop2 = np.zeros(len(Hiphop))
FeatJazz2 = np.zeros(len(Jazz))
FeatPop2 = np.zeros(len(Pop))
FeatRnb2 = np.zeros(len(Rnb))
FeatRock2 = np.zeros(len(Rock))
FeatSka2 = np.zeros(len(Ska))

In [180]:
numFeatA = 266
for i in range(0,len(FeatAsian)):
    FeatAsian1[i] = Asian[i][numFeatA]
    FeatBlues1[i] = Blues[i][numFeatA]
    FeatClassical1[i] = Classical[i][numFeatA]    
    FeatClatinamer1[i] = Clatinamer[i][numFeatA]   
    FeatCountry1[i] = Country[i][numFeatA]
    FeatEasy1[i] = Easy[i][numFeatA]
    FeatElectronic1[i] = Electronic[i][numFeatA]
    FeatFolk1[i] = Folk[i][numFeatA]
    FeatHiphop1[i] = Hiphop[i][numFeatA]
    FeatJazz1[i] = Jazz[i][numFeatA]
    FeatPop1[i] = Pop[i][numFeatA]
    FeatRnb1[i] = Rnb[i][numFeatA]
    FeatRock1[i] = Rock[i][numFeatA]
    FeatSka1[i] = Ska[i][numFeatA]

In [181]:
numFeatB = 4
for i in range(0,len(FeatAsian)):
    FeatAsian2[i] = Asian[i][numFeatB]
    FeatBlues2[i] = Blues[i][numFeatB]
    FeatClassical2[i] = Classical[i][numFeatB]    
    FeatClatinamer2[i] = Clatinamer[i][numFeatB]   
    FeatCountry2[i] = Country[i][numFeatB]
    FeatEasy2[i] = Easy[i][numFeatB]
    FeatElectronic2[i] = Electronic[i][numFeatB]
    FeatFolk2[i] = Folk[i][numFeatB]
    FeatHiphop2[i] = Hiphop[i][numFeatB]
    FeatJazz2[i] = Jazz[i][numFeatB]
    FeatPop2[i] = Pop[i][numFeatB]
    FeatRnb2[i] = Rnb[i][numFeatB]
    FeatRock2[i] = Rock[i][numFeatB]
    FeatSka2[i] = Ska[i][numFeatB]

In [207]:
ax = sns.kdeplot(FeatClassical1,FeatClassical2,cmap="Reds", shade=True,shade_lowest=False)
ax = sns.kdeplot(FeatHiphop1,FeatHiphop2,cmap="Blues", shade=True,shade_lowest=False)
ax = sns.kdeplot(FeatCountry1,FeatCountry2,cmap="Greens", shade=True,shade_lowest=False)

In [208]:
plt.show()